esphome:
  name: vbus_logger
  platform: ESP8266
  board: d1_mini
  includes:
    - resol.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.113
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "vbus_logger"
    password: !secret hotspot_pass

dallas:
  - pin: GPIO4

uart:
  id: uart_bus
  tx_pin: D6 #GPIO1
  rx_pin: D5 #GPIO3
  baud_rate: 9600

sensor:
- platform: dallas
  index: 0
  name: "1-wire sensor"

- platform: custom
  lambda: |-
    auto resol_sensor = new Resol(id(uart_bus));
    App.register_component(resol_sensor);
    return {resol_sensor->collector_temp_sensor, resol_sensor->upper_tank_temp_sensor, resol_sensor->lower_tank_temp_sensor, resol_sensor->cv_return_temp_sensor, resol_sensor->solarpump_speed_sensor, resol_sensor->cv_valve_state_sensor };

  sensors:
    - name: "collector_temp_sensor"
      unit_of_measurement: 째C
      accuracy_decimals: 1
    - name: "upper_tank_temp_sensor"
      unit_of_measurement: 째C
      accuracy_decimals: 1
    - name: "lower_tank_temp_sensor"
      unit_of_measurement: 째C
      accuracy_decimals: 1
    - name: "cv_return_temp_sensor"
      unit_of_measurement: 째C
      accuracy_decimals: 1
    - name: "solarpump_speed_sensor"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "cv_valve_state_sensor"
      unit_of_measurement: On/Off
      accuracy_decimals: 0

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:

ota: